import './globals.css'
import localFont from 'next/font/local'

const font = localFont({
  src: '../public/fonts/BIZUDMincho-Bold.woff2',
  variable: '--font-custom',
  display: 'swap',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.variable}>{children}</body>
    </html>
  )
}
